<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="E053550-VM1" name="test.cases.payroll.CheckCheckNetLT2QueryTest" tests="1" failures="0" timestamp="18 Jan 2019 18:42:31 GMT" time="0.000" errors="1">
  <testcase name="runCheckNetLT2Query" time="0.000" classname="test.cases.payroll.CheckCheckNetLT2QueryTest">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: src\main\java\data\exceldata\payroll\CheckNetLT2.xlsx">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: src\main\java\data\exceldata\payroll\CheckNetLT2.xlsx
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
Caused by: java.io.FileNotFoundException: src\main\java\data\exceldata\payroll\CheckNetLT2.xlsx
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:276)
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:252)
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:231)
	at utilities.ExcelUtils.getExcelData(ExcelUtils.java:111)
	at utilities.DataProviderUtils.getCheckNetLT2QueryFromExcel(DataProviderUtils.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 20 more
]]>
    </error>
  </testcase> <!-- runCheckNetLT2Query -->
</testsuite> <!-- test.cases.payroll.CheckCheckNetLT2QueryTest -->
